# Docker Services
services:
  # Web Application
  # (https://nuxt.com/)
  layer1guru:
    build: .
    image: layer1guru
    container_name: layer1guru
    restart: unless-stopped
    # network_mode: 'host'
    ports:
      - '127.0.0.1:3000:3000'
    #   - '0.0.0.0:80:3000'     # use without proxy server
    logging: # apply better controls to Docker overlay folder
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    # env_file: .env
    environment:
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
# Volumes
volumes:
  layer1guru:
# Networks
networks:
  layer1guru-network:
    driver: bridge
